# Generated by Django 2.2.1 on 2019-05-08 19:50

from django.db import migrations, models
import utils.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=utils.helpers.generate_short_uuid, max_length=50, unique=True, verbose_name='UID')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ('-created',),
            },
        ),
    ]
