# Generated by Django 2.2.1 on 2019-05-09 07:12

from django.db import migrations, models
import django.db.models.deletion
import utils.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=utils.helpers.generate_short_uuid, max_length=50, unique=True, verbose_name='UID')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('number', models.CharField(blank=True, max_length=32, null=True, verbose_name='Number')),
                ('title', models.TextField(verbose_name='Title')),
                ('estimated_points', models.CharField(blank=True, choices=[('0', '0'), ('1/2', '1/2'), ('1', '1'), ('2', '2'), ('3', '3'), ('5', '5'), ('8', '8'), ('13', '13'), ('20', '20'), ('40', '40'), ('100', '100'), ('?', '?')], max_length=32, null=True, verbose_name='Estimated Points')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='room.Room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
                'ordering': ('-created',),
            },
        ),
    ]
