# Generated by Django 2.2.1 on 2019-05-09 20:46

from django.db import migrations, models
import django.db.models.deletion
import utils.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=utils.helpers.generate_short_uuid, max_length=50, unique=True, verbose_name='UID')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('estimated_points', models.CharField(blank=True, choices=[('0', '0'), ('1/2', '1/2'), ('1', '1'), ('2', '2'), ('3', '3'), ('5', '5'), ('8', '8'), ('13', '13'), ('20', '20'), ('40', '40'), ('100', '100'), ('?', '?')], max_length=32, null=True, verbose_name='Estimated Points')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Issue', verbose_name='Issue')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Participant', verbose_name='Participant')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'ordering': ('-created',),
            },
        ),
    ]
