# Generated by Django 2.2.1 on 2019-05-09 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Room', verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Room', verbose_name='Room'),
        ),
    ]
