# Generated by Django 4.2.29 on 2026-03-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0013_participant_role_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='estimated_points',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1/2', '1/2'), ('1', '1'), ('2', '2'), ('3', '3'), ('5', '5'), ('8', '8'), ('13', '13'), ('20', '20'), ('40', '40'), ('100', '100'), ('?', '?'), ('21', '21'), ('34', '34'), ('55', '55'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('☕', '☕'), ('½', '½')], max_length=32, null=True, verbose_name='Estimated Points'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='estimated_points',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1/2', '1/2'), ('1', '1'), ('2', '2'), ('3', '3'), ('5', '5'), ('8', '8'), ('13', '13'), ('20', '20'), ('40', '40'), ('100', '100'), ('?', '?'), ('21', '21'), ('34', '34'), ('55', '55'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('☕', '☕'), ('½', '½')], max_length=32, null=True, verbose_name='Estimated Points'),
        ),
    ]
